---
- name: Deploy Site-B
  hosts: siteb
  become: yes

  tasks:
  - name: install docker pre-reqs
    pip:
      name: docker

  - name: launch apache-simple container on site-b nodes
    docker_container:
      name: apache-simple
      image: quay.io/nduffman/ansible-for-devops-siteb
      ports:
        - "8080:8080"

